title: "Annabelle Damerum, PhD"
tagline: "Bioinformatics • Biostatistics • Microbiome"
description: "Personal site, CV, publications, and tutorials"
url: "https://annabelledamerum.github.io"
author:
  name: "Annabelle Damerum"
  email: "annabelle.damerum@me.com"
  links:
    - label: Google Scholar
      url: https://scholar.google.com/citations?user=XlLENVYAAAAJ&hl=en&oi=ao
    - label: ORCID
      url: https://orcid.org/0000-0003-2207-4935
    - label: GitHub
      url: https://github.com/annabelledamerum
    - label: LinkedIn
      url: https://www.linkedin.com/in/annabelle-damerum/

# Pick ONE of the following theme lines (see Section 4 for options):
theme: jekyll-theme-minimal       # built-in, zero setup
# remote_theme: mmistakes/minimal-mistakes  # comment in if you choose Minimal Mistakes later

# Navigation (works with most themes)
navigation:
  - name: "About"
    link: /about
  - name: "Education"
    link: /education
  - name: "CV"
    link: /cv
  - name: "Research"
    link: /research
  - name: "Publications"
    link: /publications
  - name: "Tutorials"
    link: /tutorials/

# Collections for Tutorials (pretty URLs)
collections:
  tutorials:
    output: true
    permalink: /tutorials/:name/

# Defaults for pages/posts
defaults:
  - scope: { path: "" }
    values:
      layout: page
  - scope: { path: "tutorials" }
    values:
      layout: post
      nav_exclude: false

# Minimal custom CSS (your preferred palette)
# Elegant yet approachable palette you liked:
#  #EDC7B7 #EEE2DC #BAB2B5 #123C69 #AC3B61
sass:
  style: compressed

# Plugins: keep empty for default Pages build; see Section 6 for "any plugin"
plugins: []

# Enable the custom stylesheet
# (Some themes auto-include /assets/css/style.css; we’ll include ours manually in layouts if needed)
