title: "Annabelle Damerum, PhD"
tagline: "Bioinformatics • Biostatistics • Microbiome"
description: "Personal site, CV, publications, and tutorials"
url: "https://annabelledamerum.github.io"
baseurl: ""   

# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins supported by GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 5
paginate_path: "/page:num/"

collections:
  pages:
    output: true
    permalink: /:path/

# Theme skin + appearance
minimal_mistakes_skin: "default"  # try: "air", "aqua", "contrast", "dark", "mint", "sunrise"

# Author sidebar/profile
author:
  name: "Annabelle Damerum, Ph.D."
  avatar: "/assets/images/headshot.jpg"  # add an image or remove this line
  bio: "Bioinformatician focused on microbiome & public health genomics."
  location: "Los Angeles, CA"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=XlLENVYAAAAJ&hl=en&oi=ao"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0003-2207-4935"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/annabelledamerum"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/annabelle-damerum/"

# Navigation (top masthead) will come from _data/navigation.yml

# Defaults so pages use the theme’s layouts nicely
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Optional search (Lunr.js built-in)
search: true

# Permalinks (good for breadcrumbs and archives)
permalink: /:categories/:title/